#!/usr/bin/env python3
"""
Automated PR Creator for Pulse Incidents
Watches pulse.db for resolved incidents and creates GitHub PRs automatically.
"""
import sqlite3
import time
import subprocess
import json
from datetime import datetime
from pathlib import Path

DB_PATH = Path(__file__).parent / "pulse.db"
PROCESSED_FILE = Path(__file__).parent / ".processed_incidents.json"

def load_processed_incidents():
    """Load list of already processed incident IDs."""
    if PROCESSED_FILE.exists():
        with open(PROCESSED_FILE, 'r') as f:
            return set(json.load(f))
    return set()

def save_processed_incident(incident_id):
    """Mark an incident as processed."""
    processed = load_processed_incidents()
    processed.add(incident_id)
    with open(PROCESSED_FILE, 'w') as f:
        json.dump(list(processed), f, indent=2)

def get_resolved_incidents():
    """Get all resolved incidents that haven't been processed yet."""
    processed = load_processed_incidents()
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    
    incidents = conn.execute("""
        SELECT * FROM incidents 
        WHERE status IN ('resolved', 'auto_resolved')
        AND id NOT IN ({})
        ORDER BY resolved_at DESC
    """.format(','.join('?' * len(processed)) if processed else '""'), 
    tuple(processed) if processed else ()).fetchall()
    
    conn.close()
    return [dict(inc) for inc in incidents]

def create_incident_doc(incident):
    """Create a markdown document for the incident."""
    inc_id = incident['id']
    service = incident['service']
    title = incident['title']
    
    # Parse steps
    steps = json.loads(incident.get('steps', '[]'))
    steps_md = '\n'.join([f"- {step['text']}" for step in steps])
    
    # Get RCA details
    what = incident.get('rca_what', 'N/A')
    timeline = incident.get('rca_timeline', 'N/A')
    root_cause = incident.get('rca_root_cause', 'N/A')
    confidence = incident.get('rca_confidence', 0)
    action_taken = incident.get('rca_action', 'N/A')
    
    # Parse recommended actions
    rec_actions = json.loads(incident.get('recommended_actions', '[]'))
    rec_actions_md = '\n'.join([f"- {action}" for action in rec_actions]) if rec_actions else "None"
    
    doc = f"""# Incident Report: {inc_id}

## Overview
- **Service**: {service}
- **Title**: {title}
- **Severity**: {incident.get('severity', 'N/A')}
- **Status**: {incident['status']}
- **Triggered At**: {incident.get('triggered_at', 'N/A')}
- **Resolved At**: {incident.get('resolved_at', 'N/A')}

## Problem Description
{what}

## Investigation Steps
{steps_md}

## Root Cause Analysis
**Root Cause**: {root_cause}

**Confidence**: {confidence}%

**Timeline**: {timeline}

## Resolution
**Action Taken**: {action_taken}

## Recommended Actions
{rec_actions_md}

---
*This incident report was automatically generated by Pulse AI Incident Management System*
"""
    return doc

def create_pr_for_incident(incident):
    """Create a GitHub PR for a resolved incident."""
    inc_id = incident['id']
    service = incident['service']
    branch_name = f"incident/{inc_id.lower()}"
    
    print(f"\n[AUTO-PR] Creating PR for {inc_id}...")
    
    try:
        # Create and checkout new branch
        subprocess.run(['git', 'checkout', '-b', branch_name], check=True, capture_output=True)
        print(f"[AUTO-PR] Created branch: {branch_name}")
        
        # Create incidents directory if it doesn't exist
        incidents_dir = Path(__file__).parent / "incidents"
        incidents_dir.mkdir(exist_ok=True)
        
        # Write incident document
        doc_path = incidents_dir / f"{inc_id}.md"
        doc_content = create_incident_doc(incident)
        doc_path.write_text(doc_content)
        print(f"[AUTO-PR] Created document: {doc_path}")
        
        # Git add, commit, push
        subprocess.run(['git', 'add', str(doc_path)], check=True)
        commit_msg = f"docs: Add incident report for {inc_id} - {service}"
        subprocess.run(['git', 'commit', '-m', commit_msg], check=True)
        print(f"[AUTO-PR] Committed changes")
        
        subprocess.run(['git', 'push', '-u', 'origin', branch_name], check=True)
        print(f"[AUTO-PR] Pushed to origin/{branch_name}")
        
        # Create PR using GitHub CLI if available, otherwise provide instructions
        pr_title = f"Incident Report: {inc_id} - {service}"
        pr_body = f"""## Incident Summary
- **ID**: {inc_id}
- **Service**: {service}
- **Root Cause**: {incident.get('rca_root_cause', 'N/A')}
- **Status**: {incident['status']}

This PR documents the incident investigation and resolution.

See the full report in `incidents/{inc_id}.md`
"""
        
        # Try to create PR with gh CLI
        try:
            result = subprocess.run([
                'gh', 'pr', 'create',
                '--title', pr_title,
                '--body', pr_body,
                '--base', 'main',
                '--head', branch_name
            ], check=True, capture_output=True, text=True)
            pr_url = result.stdout.strip()
            print(f"[AUTO-PR] ✅ PR created: {pr_url}")
        except (subprocess.CalledProcessError, FileNotFoundError):
            print(f"[AUTO-PR] ⚠️  GitHub CLI not available. PR not created automatically.")
            print(f"[AUTO-PR] 📝 Manual PR creation needed:")
            print(f"[AUTO-PR]    Branch: {branch_name}")
            print(f"[AUTO-PR]    URL: https://github.com/ngv2003/pulse-incident-management/compare/{branch_name}?expand=1")
        
        # Switch back to main
        subprocess.run(['git', 'checkout', 'main'], check=True, capture_output=True)
        
        # Mark as processed
        save_processed_incident(inc_id)
        print(f"[AUTO-PR] ✅ Completed processing {inc_id}\n")
        
        return True
        
    except subprocess.CalledProcessError as e:
        print(f"[AUTO-PR] ❌ Error creating PR: {e}")
        # Try to switch back to main
        try:
            subprocess.run(['git', 'checkout', 'main'], capture_output=True)
        except:
            pass
        return False

def watch_and_create_prs():
    """Main loop: watch for resolved incidents and create PRs."""
    print("=" * 60)
    print("🤖 Pulse Auto-PR Creator Started")
    print("=" * 60)
    print(f"Watching: {DB_PATH}")
    print(f"Checking every 10 seconds for resolved incidents...")
    print("Press Ctrl+C to stop\n")
    
    while True:
        try:
            resolved = get_resolved_incidents()
            
            if resolved:
                print(f"[AUTO-PR] Found {len(resolved)} new resolved incident(s)")
                for incident in resolved:
                    create_pr_for_incident(incident)
            
            time.sleep(10)  # Check every 10 seconds
            
        except KeyboardInterrupt:
            print("\n[AUTO-PR] Stopping auto-PR creator...")
            break
        except Exception as e:
            print(f"[AUTO-PR] Error: {e}")
            time.sleep(10)

if __name__ == "__main__":
    watch_and_create_prs()

# Made with Bob
